### ISSUE TITLE
Snapshot building failed after merge

### ISSUE THREAD

**Issue by marvinmirtschin** [neXenio/BLE-Indoor-Positioning#61]
/home/jitpack/build/BLE Indoor Positioning/src/main/java/com/nexenio/bleindoorpositioning/location/distance/BeaconDistanceCalculator.java:16: error: no tag name after @
     * @ see <a href="https://en.wikipedia.org/wiki/Log-distance_path_loss_model"></a>
       ^
